http_port = 9081

[db]
dsn = "host=localhost user=postgres password=postgres dbname=yantube port=5432 sslmode=disable"

[user]
allow_register = true
auth_realm = "stream api"
auth_secret = "secret"

[srs]
api_url = "http://srs:1985"
api_user = "admin"
api_password = "admin"
callback_secret = "secret"

[metrics]
enabled = true
