ALTER TABLE IF EXISTS live_room
ADD COLUMN IF NOT EXISTS require_login BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE IF EXISTS live_room
ADD COLUMN IF NOT EXISTS password_hash TEXT NOT NULL DEFAULT '';

ALTER TABLE IF EXISTS live_room
ADD COLUMN IF NOT EXISTS access_revision INTEGER NOT NULL DEFAULT 0;
